
package ru.suleiemnov.consumesoapmessageservice.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "UserServicePort", targetNamespace = "http://sdr.com/spring-soap-example")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserServicePort {


    /**
     * 
     * @param getUserRequest
     * @return
     *     returns ru.suleiemnov.consumesoapmessageservice.wsdl.GetUserResponse
     */
    @WebMethod
    @WebResult(name = "getUserResponse", targetNamespace = "http://sdr.com/spring-soap-example", partName = "getUserResponse")
    public GetUserResponse getUser(
        @WebParam(name = "getUserRequest", targetNamespace = "http://sdr.com/spring-soap-example", partName = "getUserRequest")
        GetUserRequest getUserRequest);

}
